default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - echo $CI_REGISTRY
    - docker login -u $CI_CUSTOM_REGISTRY_USER -p $CI_CUSTOM_REGISTRY_PASS $CI_CUSTOM_REGISTRY

variables:
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t $CI_CUSTOM_REGISTRY/hiorg-fe2/app:latest-dev .
    - docker push $CI_CUSTOM_REGISTRY/hiorg-fe2/app:latest-dev
deploy-dev:
  stage: deploy
  #image: junte/ssh-agent
  variables:
    # should be set up at Gitlab CI env vars
    SSH_PRIVATE_KEY: $SSH_DEV_PRIVATE_KEY
  script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_DEV_PRIVATE_KEY"
    - ssh-add "$SSH_DEV_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh root@iuk-wuerzburg.de "cd /var/docker/sync/ && docker compose pull web && docker compose up -d"
