default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - echo $CI_REGISTRY
    - docker login -u $CI_CUSTOM_REGISTRY_USER -p $CI_CUSTOM_REGISTRY_PASS $CI_CUSTOM_REGISTRY

variables:
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build
  - test
  - deploy

build-branch:
  stage: build
  except:
    - tags
    - main
    - merge_requests
  script:
    - docker build --cache-from $CI_CUSTOM_REGISTRY/hiorg-fe2/app:latest-dev -t $CI_CUSTOM_REGISTRY/hiorg-fe2/app:$CI_COMMIT_BRANCH .
    - docker push $CI_CUSTOM_REGISTRY/hiorg-fe2/app:$CI_COMMIT_BRANCH

build-dev:
  stage: build
  only:
    - main
  script:
    - docker build --cache-from $CI_CUSTOM_REGISTRY/hiorg-fe2/app:latest-dev -t $CI_CUSTOM_REGISTRY/hiorg-fe2/app:latest-dev .
    - docker push $CI_CUSTOM_REGISTRY/hiorg-fe2/app:latest-dev
build-prod:
  stage: build
  only:
    - tags
  script:
    - docker build --cache-from $CI_CUSTOM_REGISTRY/hiorg-fe2/app:latest-dev -t $CI_CUSTOM_REGISTRY/hiorg-fe2/app:latest .
    - docker push $CI_CUSTOM_REGISTRY/hiorg-fe2/app:latest


test-branch:
  stage: test
  before_script: []
  image: $CI_CUSTOM_REGISTRY/hiorg-fe2/app:$CI_COMMIT_BRANCH
  except:
    - tags
    - main
    - merge_requests
  script:
    - composer install
    - php artisan key:generate
    - ./vendor/bin/phpunit --configuration phpunit.xml
deploy-dev:
  stage: deploy
  only:
    - main
  variables:
    SSH_PRIVATE_KEY: $SSH_DEV_PRIVATE_KEY
  script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_DEV_PRIVATE_KEY"
    - ssh-add "$SSH_DEV_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh -o StrictHostKeyChecking=no root@iuk-wuerzburg.de "cd /var/docker/sync-dev/ && docker compose pull web && docker compose up -d"
    - ssh -o StrictHostKeyChecking=no root@iuk-wuerzburg.de "cd /var/docker/sync-dev/ && docker compose exec web php artisan migrate --force"

deploy-prod:
  stage: deploy
  only:
    - tags
  variables:
    SSH_PRIVATE_KEY: $SSH_DEV_PRIVATE_KEY
  script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_DEV_PRIVATE_KEY"
    - ssh-add "$SSH_DEV_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh -o StrictHostKeyChecking=no root@iuk-wuerzburg.de "cd /var/docker/sync/ && docker compose pull web && docker compose up -d"
    - ssh -o StrictHostKeyChecking=no root@iuk-wuerzburg.de "cd /var/docker/sync/ && docker compose exec web php artisan migrate --force"
